### ISSUE TITLE
Tags not visible after a certain number

### ISSUE THREAD

**Issue by realrubberduckdev** [JaeYeopHan/gatsby-starter-bee#61] opened 2019-10-09 20:12 UTC
## Description
![image](https://user-images.githubusercontent.com/22910832/66516634-641dfb00-ead9-11e9-925b-bd4a7fb54a2c.png)

Is there any recommended way of fixing this?

**Comment by JaeYeopHan** [comment] 2019-10-10 01:42
@dp7g09 hi,
Could you tell me more exactly what the problem is?

**Comment by dp7g09** [comment] 2019-10-10 05:52
Hi @JaeYeopHan
Thanks for quick response.

The issue is if I add more than five tags, the new ones are not visible. Basically add six or seven posts with different tags (or known as category) and you'll see the issue.

As shown in the screenshot above.

Hope this helps.

**Comment by JaeYeopHan** [comment] 2019-10-10 06:15
> the new ones are not visible

I'm not sure what it means to be `not visible`.

That area is available to scroll (horizontal).
![1](https://user-images.githubusercontent.com/17924127/66543532-9595d580-eb70-11e9-8bfc-0957557543cc.gif)

**Comment by dp7g09** [comment] 2019-10-10 06:17
Wow ok. I must have missed the scrolling then, sorry for wasting your time. Not at desk now will try it get back to you today to confirm.

**Comment by dp7g09** [comment] 2019-10-10 09:52
@JaeYeopHan Hi, I tried it again, the scroll doesn't actually work for me. I have not changed anything apart from adding new posts.

![beestarter](https://user-images.githubusercontent.com/22910832/66558766-08408a00-eb4c-11e9-9511-d9cb46ea1a96.gif)


I might not use this starter, so if this issue is specific to my setup, happy to close it. Or if you need further info to fix it, happy to help. Your call.

**Comment by JaeYeopHan** [comment] 2019-10-10 09:58
@dp7g09 ok ;) Could you tell me your environment and browser?

**Comment by dp7g09** [comment] 2019-10-10 10:30
Using Windows 10 Pro 1803 build. Chrome browser. Just FYI, I also tried on incognito mode and the scrolling doesn't work.

**Comment by JaeYeopHan** [comment] 2020-07-12 06:42
![test](https://user-images.githubusercontent.com/17924127/87240640-33973300-c456-11ea-89e3-d5f326597175.gif)

solved? :)

**Closed by JaeYeopHan** 2020-07-12 06:42 UTC
Labels: question
